### ISSUE TITLE
Shop Suggestions

### ISSUE THREAD

**Issue by LozMoz** [SilentRoses/Farnetworks#100]
aNem0:
Add Bamboo
Add Hoppers (on opsbee)

Kieranbroadribs:
Add Concrete
Add Shulkers (since a portion of the servers dont have end cities)

**Comment by SilentRoses** [comment]
Hoppers are on opsbee store the rest is on to-do list

**Comment by LozMoz** [comment]
also might want to add beetroot seeds to opsbee since cant obtain from villages

**Comment by Fiend-V** [comment]
Added Bamboo, Beetroot seeds, Shulker Boxes (On OPSBEE) and all colored concrete blocks on OPSBEE and BeeSMP.
And no, Hoppers are not in the shops on opsbee.
Will add them at 25k to buy. If price change desired, feel free to change.
Shulker boxes will be left off shop on BeeSMP due to end cities being present and pre-existing shulker farms.
